// Code generated by ax-spec. DO NOT EDIT.

package ax

// Capability represents an operation capability for agent introspection.
type Capability string

// Standard capabilities derived from operation semantics.
const (
	CapRead   Capability = "read"
	CapWrite  Capability = "write"
	CapDelete Capability = "delete"
	CapAdmin  Capability = "admin"
)

// OperationCapabilities maps operation IDs to their capabilities.
// Capabilities indicate what an operation can do:
//   - read: retrieves data without modification
//   - write: creates or modifies data
//   - delete: removes data
//   - admin: administrative operations requiring elevated permissions
var OperationCapabilities = map[string][]Capability{
	// Voice operations
	"get_voices":          {CapRead},
	"get_voice_by_id":     {CapRead},
	"add_voice":           {CapWrite},
	"edit_voice":          {CapWrite},
	"delete_voice":        {CapWrite, CapDelete},
	"get_voice_settings":  {CapRead},
	"edit_voice_settings": {CapWrite},

	// Text-to-speech operations
	"text_to_speech_full":   {CapWrite},
	"text_to_speech_stream": {CapWrite},
	"text_to_dialogue":      {CapWrite},

	// Speech-to-text operations
	"speech_to_text": {CapWrite},

	// History operations
	"get_speech_history":            {CapRead},
	"get_speech_history_item_by_id": {CapRead},
	"delete_speech_history_item":    {CapWrite, CapDelete},
	"download_speech_history_items": {CapRead},

	// Model operations
	"get_models": {CapRead},

	// User operations
	"get_user_info":              {CapRead},
	"get_user_subscription_info": {CapRead},

	// Project operations
	"get_projects":      {CapRead},
	"get_project_by_id": {CapRead},
	"add_project":       {CapWrite},
	"delete_project":    {CapWrite, CapDelete},
	"edit_project":      {CapWrite},

	// Dubbing operations
	"create_dubbing":  {CapWrite},
	"delete_dubbing":  {CapWrite, CapDelete},
	"get_dubbed_file": {CapRead},
	"list_dubs":       {CapRead},

	// Sound effects
	"sound_generation": {CapWrite},

	// Audio isolation
	"audio_isolation":        {CapWrite},
	"audio_isolation_stream": {CapWrite},

	// Voice design
	"text_to_voice":         {CapWrite},
	"text_to_voice_design":  {CapWrite},
	"generate_random_voice": {CapWrite},

	// Pronunciation
	"get_pronunciation_dictionaries_metadata": {CapRead},
	"get_pronunciation_dictionary_metadata":   {CapRead},
	"patch_pronunciation_dictionary":          {CapWrite},

	// Agents (Conversational AI)
	"get_agents_route":      {CapRead},
	"get_agent_route":       {CapRead},
	"create_agent_route":    {CapWrite},
	"delete_agent_route":    {CapWrite, CapDelete},
	"duplicate_agent_route": {CapWrite},

	// Workspace/Admin operations
	"get_workspace_service_accounts": {CapRead, CapAdmin},
	"create_service_account_api_key": {CapWrite, CapAdmin},
	"delete_service_account_api_key": {CapWrite, CapDelete, CapAdmin},
	"invite_user":                    {CapWrite, CapAdmin},
	"remove_member":                  {CapWrite, CapDelete, CapAdmin},
}

// GetCapabilities returns the capabilities for an operation.
// Returns nil if the operation is not found.
func GetCapabilities(operationID string) []Capability {
	return OperationCapabilities[operationID]
}

// HasCapability checks if an operation has a specific capability.
func HasCapability(operationID string, cap Capability) bool {
	caps := OperationCapabilities[operationID]
	for _, c := range caps {
		if c == cap {
			return true
		}
	}
	return false
}

// IsReadOnly returns true if an operation only has read capability.
func IsReadOnly(operationID string) bool {
	caps := OperationCapabilities[operationID]
	if len(caps) == 0 {
		return false
	}
	for _, c := range caps {
		if c != CapRead {
			return false
		}
	}
	return true
}

// RequiresAdmin returns true if an operation requires admin capability.
func RequiresAdmin(operationID string) bool {
	return HasCapability(operationID, CapAdmin)
}

// GetOperationsByCapability returns all operations that have a specific capability.
func GetOperationsByCapability(cap Capability) []string {
	var ops []string
	for op, caps := range OperationCapabilities {
		for _, c := range caps {
			if c == cap {
				ops = append(ops, op)
				break
			}
		}
	}
	return ops
}
