// Package ax provides Agent Experience (AX) metadata for the ElevenLabs API.
//
// This package is generated by ax-spec from x-ax-* OpenAPI extensions and API
// discovery. It provides:
//
//   - Error code constants for machine-readable error handling
//   - Retry policies indicating which operations are safe to retry
//   - Capability mappings for operation introspection
//   - Required field validation for request bodies
//
// Error Handling Example:
//
//	import "github.com/plexusone/elevenlabs-go/ax"
//
//	resp, err := client.TextToSpeech().Generate(ctx, req)
//	if err != nil {
//	    apiErr := elevenlabs.ParseAPIError(err)
//	    if apiErr != nil && ax.IsErrorCode(apiErr, ax.ErrDocumentNotFound) {
//	        // Handle specific error
//	    }
//	}
//
// Retry Policy Example:
//
//	if ax.IsRetryable("get_voices") {
//	    // Safe to implement automatic retry
//	}
//
// The error codes were discovered by making actual API calls to the ElevenLabs
// API and extracting error codes from responses. This provides more accurate
// metadata than can be inferred from the OpenAPI specification alone.
package ax
