// Code generated by ax-spec. DO NOT EDIT.

package ax

import "strings"

// Error codes discovered from the ElevenLabs API via x-ax-error-code extensions.
// These codes appear in API error responses and can be used for machine-readable
// error handling instead of parsing error messages.
const (
	// ErrDocumentNotFound indicates the requested document was not found.
	ErrDocumentNotFound = "DOCUMENT_NOT_FOUND"

	// ErrInvalidUID indicates the provided UID is invalid.
	ErrInvalidUID = "INVALID_UID"

	// ErrMissingFeedback indicates feedback is required but was not provided.
	ErrMissingFeedback = "MISSING_FEEDBACK"

	// ErrNeedsAuthorization indicates the operation requires additional authorization.
	ErrNeedsAuthorization = "NEEDS_AUTHORIZATION"

	// ErrNotLoggedIn indicates the user is not authenticated.
	ErrNotLoggedIn = "NOT_LOGGED_IN"

	// ErrNoEditChanges indicates no changes were provided for an edit operation.
	ErrNoEditChanges = "NO_EDIT_CHANGES"

	// ErrUnprocessableEntity indicates a validation error in the request.
	ErrUnprocessableEntity = "UNPROCESSABLE_ENTITY"

	// ErrUserNotFound indicates the specified user was not found.
	ErrUserNotFound = "USER_NOT_FOUND"

	// ErrWorkspaceNotFound indicates the specified workspace was not found.
	ErrWorkspaceNotFound = "WORKSPACE_NOT_FOUND"
)

// AllErrorCodes contains all known ElevenLabs API error codes.
var AllErrorCodes = []string{
	ErrDocumentNotFound,
	ErrInvalidUID,
	ErrMissingFeedback,
	ErrNeedsAuthorization,
	ErrNotLoggedIn,
	ErrNoEditChanges,
	ErrUnprocessableEntity,
	ErrUserNotFound,
	ErrWorkspaceNotFound,
}

// ErrorCodeInfo provides metadata about an error code.
type ErrorCodeInfo struct {
	Code        string
	Description string
	Retryable   bool
	Category    string
}

// ErrorCodeMetadata maps error codes to their metadata.
var ErrorCodeMetadata = map[string]ErrorCodeInfo{
	ErrDocumentNotFound: {
		Code:        ErrDocumentNotFound,
		Description: "The requested document was not found",
		Retryable:   false,
		Category:    "not_found",
	},
	ErrInvalidUID: {
		Code:        ErrInvalidUID,
		Description: "The provided UID is invalid",
		Retryable:   false,
		Category:    "validation",
	},
	ErrMissingFeedback: {
		Code:        ErrMissingFeedback,
		Description: "Feedback is required but was not provided",
		Retryable:   false,
		Category:    "validation",
	},
	ErrNeedsAuthorization: {
		Code:        ErrNeedsAuthorization,
		Description: "The operation requires additional authorization",
		Retryable:   false,
		Category:    "auth",
	},
	ErrNotLoggedIn: {
		Code:        ErrNotLoggedIn,
		Description: "The user is not authenticated",
		Retryable:   false,
		Category:    "auth",
	},
	ErrNoEditChanges: {
		Code:        ErrNoEditChanges,
		Description: "No changes were provided for the edit operation",
		Retryable:   false,
		Category:    "validation",
	},
	ErrUnprocessableEntity: {
		Code:        ErrUnprocessableEntity,
		Description: "Request validation failed",
		Retryable:   false,
		Category:    "validation",
	},
	ErrUserNotFound: {
		Code:        ErrUserNotFound,
		Description: "The specified user was not found",
		Retryable:   false,
		Category:    "not_found",
	},
	ErrWorkspaceNotFound: {
		Code:        ErrWorkspaceNotFound,
		Description: "The specified workspace was not found",
		Retryable:   false,
		Category:    "not_found",
	},
}

// APIErrorer is an interface for errors that provide API error details.
// The elevenlabs.APIError type implements this interface.
type APIErrorer interface {
	error
	APIDetail() string
	APIMessage() string
}

// IsErrorCode checks if an error contains the specified AX error code.
// It works with any error type by checking if the error string contains the code.
// For more precise matching, use IsErrorCodeExact with an APIErrorer.
func IsErrorCode(err error, code string) bool {
	if err == nil {
		return false
	}
	return strings.Contains(err.Error(), code)
}

// ContainsErrorCode extracts the AX error code from an error, if present.
// Returns the matching code and true if found, empty string and false otherwise.
func ContainsErrorCode(err error) (string, bool) {
	if err == nil {
		return "", false
	}
	errStr := err.Error()
	for _, code := range AllErrorCodes {
		if strings.Contains(errStr, code) {
			return code, true
		}
	}
	return "", false
}

// GetErrorInfo returns metadata about an error code.
// Returns nil if the code is not recognized.
func GetErrorInfo(code string) *ErrorCodeInfo {
	if info, ok := ErrorCodeMetadata[code]; ok {
		return &info
	}
	return nil
}

// IsAuthError returns true if the error code indicates an authentication/authorization issue.
func IsAuthError(code string) bool {
	info := GetErrorInfo(code)
	return info != nil && info.Category == "auth"
}

// IsNotFoundError returns true if the error code indicates a resource was not found.
func IsNotFoundError(code string) bool {
	info := GetErrorInfo(code)
	return info != nil && info.Category == "not_found"
}

// IsValidationError returns true if the error code indicates a validation failure.
func IsValidationError(code string) bool {
	info := GetErrorInfo(code)
	return info != nil && info.Category == "validation"
}
