// Code generated by ax-spec. DO NOT EDIT.

package ax

// RequiredFields maps operation IDs to their required input fields.
// This is extracted from the OpenAPI specification's requestBody schema
// required fields, allowing pre-flight validation before making API calls.
var RequiredFields = map[string][]string{
	"add_chapter":                              {"name"},
	"add_from_rules":                           {"rules", "name"},
	"add_language":                             {"language"},
	"add_mcp_server_tool_approval_route":       {"tool_name", "tool_description"},
	"add_mcp_tool_config_override_route":       {"tool_name"},
	"add_member":                               {"email"},
	"add_rules":                                {"rules"},
	"add_sharing_voice":                        {"new_name"},
	"add_tool_route":                           {"tool_config"},
	"compose_plan":                             {"prompt"},
	"create_agent_response_test_route":         {"chat_history", "success_condition", "success_examples", "failure_examples", "name"},
	"create_agent_route":                       {"conversation_config"},
	"create_batch_call":                        {"call_name", "agent_id", "recipients"},
	"create_clip":                              {"start_time", "end_time"},
	"create_mcp_server_route":                  {"config"},
	"create_podcast":                           {"model_id", "mode", "source"},
	"create_pvc_voice":                         {"name", "language"},
	"create_secret_route":                      {"type", "name", "value"},
	"create_service_account_api_key":           {"name", "permissions"},
	"create_text_document_route":               {"text"},
	"create_url_document_route":                {"url"},
	"create_voice":                             {"voice_name", "voice_description", "generated_voice_id"},
	"create_voice_old":                         {"voice_name", "voice_description", "generated_voice_id"},
	"create_workspace_webhook_route":           {"settings"},
	"download_speech_history_items":            {"history_item_ids"},
	"dub":                                      {"segments", "languages"},
	"edit_project":                             {"name", "default_title_voice_id", "default_paragraph_voice_id"},
	"edit_service_account_api_key":             {"is_enabled", "name", "permissions"},
	"edit_workspace_webhook_route":             {"is_disabled", "name"},
	"generate_random_voice":                    {"gender", "accent", "age", "accent_strength", "text"},
	"get_agent_response_tests_summaries_route": {"test_ids"},
	"get_or_create_rag_indexes":                {"items"},
	"get_public_llm_expected_cost_calculation": {"prompt_length", "number_of_pages", "rag_enabled"},
	"handle_sip_trunk_outbound_call":           {"agent_id", "agent_phone_number_id", "to_number"},
	"handle_twilio_outbound_call":              {"agent_id", "agent_phone_number_id", "to_number"},
	"import_whatsapp_account":                  {"business_account_id", "phone_number_id", "token_code"},
	"invite_user":                              {"email"},
	"invite_users_bulk":                        {"emails"},
	"migrate_segments":                         {"segment_ids", "speaker_id"},
	"rag_index_status":                         {"model"},
	"register_twilio_call":                     {"agent_id", "from_number", "to_number"},
	"remove_member":                            {"email"},
	"remove_rules":                             {"rule_strings"},
	"render":                                   {"render_type"},
	"resubmit_tests_route":                     {"test_run_ids", "agent_id"},
	"run_agent_test_suite_route":               {"tests"},
	"run_conversation_simulation_route":        {"simulation_specification"},
	"run_conversation_simulation_route_stream": {"simulation_specification"},
	"share_resource_endpoint":                  {"role", "resource_type"},
	"sound_generation":                         {"text"},
	"text_to_dialogue":                         {"inputs"},
	"text_to_dialogue_full_with_timestamps":    {"inputs"},
	"text_to_dialogue_stream":                  {"inputs"},
	"text_to_dialogue_stream_with_timestamps":  {"inputs"},
	"text_to_speech_full":                      {"text"},
	"text_to_speech_full_with_timestamps":      {"text"},
	"text_to_speech_stream":                    {"text"},
	"text_to_speech_stream_with_timestamps":    {"text"},
	"text_to_voice":                            {"voice_description"},
	"text_to_voice_design":                     {"voice_description"},
	"text_to_voice_remix":                      {"voice_description"},
	"transcribe":                               {"segments"},
	"translate":                                {"segments", "languages"},
	"unshare_resource_endpoint":                {"resource_type"},
	"update_agent_response_test_route":         {"chat_history", "success_condition", "success_examples", "failure_examples", "name"},
	"update_document_route":                    {"name"},
	"update_mcp_server_approval_policy_route":  {"approval_policy"},
	"update_pronunciation_dictionaries":        {"pronunciation_dictionary_locators"},
	"update_secret_route":                      {"type", "name", "value"},
	"update_tool_route":                        {"tool_config"},
	"update_workspace_member":                  {"email"},
	"whatsapp_outbound_call":                   {"whatsapp_phone_number_id", "whatsapp_user_id", "whatsapp_call_permission_request_template_name", "whatsapp_call_permission_request_template_language_code", "agent_id"},
}

// GetRequiredFields returns the required fields for an operation.
// Returns nil if the operation has no required fields or is not found.
func GetRequiredFields(operationID string) []string {
	return RequiredFields[operationID]
}

// HasRequiredFields returns true if the operation has required fields.
func HasRequiredFields(operationID string) bool {
	fields := RequiredFields[operationID]
	return len(fields) > 0
}

// MissingFields checks which required fields are missing from a request.
// The provided map should contain the field names that are present.
// Returns a slice of missing field names.
func MissingFields(operationID string, presentFields map[string]bool) []string {
	required := RequiredFields[operationID]
	if len(required) == 0 {
		return nil
	}

	var missing []string
	for _, field := range required {
		if !presentFields[field] {
			missing = append(missing, field)
		}
	}
	return missing
}

// ValidateFields returns an error message if required fields are missing.
// Returns empty string if all required fields are present.
func ValidateFields(operationID string, presentFields map[string]bool) string {
	missing := MissingFields(operationID, presentFields)
	if len(missing) == 0 {
		return ""
	}

	if len(missing) == 1 {
		return "missing required field: " + missing[0]
	}

	result := "missing required fields: "
	for i, field := range missing {
		if i > 0 {
			result += ", "
		}
		result += field
	}
	return result
}
